lxqt changes for autologin session

diff --git a/debian/fll-live-initscripts.fll-desktop.init b/debian/fll-live-initscripts.fll-desktop.init
--- a/debian/fll-live-initscripts.fll-desktop.init
+++ b/debian/fll-live-initscripts.fll-desktop.init
@@ -31,11 +31,11 @@ NAME="fll-desktop"
 FLL_DISTRO_MODE="installed"
 
 if [ -r /etc/default/distro ]; then
-	. /etc/default/distro
+    . /etc/default/distro
 fi
 
 if [ "${FLL_DISTRO_MODE}" != "live" ]; then
-	exit 0
+    exit 0
 fi
 
 ###
@@ -57,156 +57,157 @@ fi
 # cheatcode handling
 ###
 if [ -f /proc/cmdline ]; then
-	for param in $(cat /proc/cmdline); do
-		case "${param}" in
-			flldebug=*)
-				if [ "${param#flldebug=}" = "${NAME#fll-}" ] || [ "${param#flldebug=}" = "all" ]; then
-					fll_redirect
-				fi
-				;;
-			desktop=*)
-				DESKTOP="${param#desktop=}"
-				;;
-		esac
-	done
+    for param in $(cat /proc/cmdline); do
+        case "${param}" in
+            flldebug=*)
+                if [ "${param#flldebug=}" = "${NAME#fll-}" ] || [ "${param#flldebug=}" = "all" ]; then
+                    fll_redirect
+                fi
+                ;;
+            desktop=*)
+                DESKTOP="${param#desktop=}"
+		;;
+        esac
+    done
 fi
 
 if [ -z "${DESKTOP}" ]; then
-	[ -x "/usr/bin/icewm" ] && DESKTOP="icewm"		# sixth choice
-	[ -x "/usr/bin/startfluxbox" ] && DESKTOP="fluxbox"	# fifth choice
-	[ -x "/usr/bin/startlxde" ] && \
-	[ -x "/usr/bin/openbox" ] && DESKTOP="lxde"	        # fourth choice
-	[ -x "/usr/bin/xfwm4" ] && DESKTOP="xfce"		# third choice
-	[ -x "/usr/bin/metacity" ] && DESKTOP="gnome"		# second choice
-	[ -x "/usr/bin/kwin" ] && DESKTOP="kde"			# first choice, if installed and desktop= is empty
-	[ -x "/usr/bin/razor-session" ] && DESKTOP="razorqt"    # seventh choice
-	[ -x "/usr/bin/cinnamon" ] && DESKTOP="cinnamon"        # eight choice
-        [ -x "/usr/bin/lxqt-session" ] && DESKTOP="lxde-qt"     # nineth choice
-	# none of the major desktop environments is installed, don't interfere 
-	# with ordinary priorities.
-	[ -z "${DESKTOP}" ] && exit 0
+    [ -x "/usr/bin/icewm" ] && DESKTOP="icewm"		# sixth choice
+    [ -x "/usr/bin/startfluxbox" ] && DESKTOP="fluxbox"	# fifth choice
+    [ -x "/usr/bin/startlxde" ] && \
+    [ -x "/usr/bin/openbox" ] && DESKTOP="lxde"	        # fourth choice
+    [ -x "/usr/bin/xfwm4" ] && DESKTOP="xfce"		# third choice
+    [ -x "/usr/bin/metacity" ] && DESKTOP="gnome"		# second choice
+    [ -x "/usr/bin/kwin" ] && DESKTOP="kde"			# first choice, if installed and desktop= is empty
+    [ -x "/usr/bin/razor-session" ] && DESKTOP="razorqt"    # seventh choice
+    [ -x "/usr/bin/cinnamon" ] && DESKTOP="cinnamon"        # eight choice
+    [ -x "/usr/bin/lxqt-session" ] && DESKTOP="lxqt"        # nineth choice
+    # none of the major desktop environments is installed, don't interfere 
+    # with ordinary priorities.
+    [ -z "${DESKTOP}" ] && exit 0
 fi
 
 do_start() {
-	FLL_LIVE_USER_GROUP=$(getent passwd ${FLL_LIVE_USER} | cut -d\: -f 4)
-	FLL_LIVE_USER_HOME=$(getent passwd ${FLL_LIVE_USER} | cut -d\: -f 6)
+    FLL_LIVE_USER_GROUP=$(getent passwd ${FLL_LIVE_USER} | cut -d\: -f 4)
+    FLL_LIVE_USER_HOME=$(getent passwd ${FLL_LIVE_USER} | cut -d\: -f 6)
 
-	log_daemon_msg "${NAME}"
+    log_daemon_msg "${NAME}"
 
-	case "${DESKTOP}" in 
-		cinnamon)
-			WM="/usr/bin/gnome-session-cinnamon"
-			;;
-		flux*)
-			WM="/usr/bin/startfluxbox"
-			;;
-		gnome)
-			WM="/usr/bin/metacity"
-			;;
-		icewm)
-			WM="/usr/bin/icewm"
-			;;
-		kde)
-			WM="/usr/bin/kwin"
-			;;
-		lxde)
-			WM="/usr/bin/openbox"
-			;;
-		xfce)
-			WM="/usr/bin/xfwm4"
-			;;
-		razorqt)
-			WM="/usr/bin/razor-session"
-			;;
-                lxde-qt)  WM="/usr/bin/lxqt-session"
-                        ;;
-		*)
-			log_action_msg " desktop '${DESKTOP}' is not available"
-			log_end_msg 0
-			return 1
-			;;
-	esac
+    case "${DESKTOP}" in
+        cinnamon)
+            WM="/usr/bin/gnome-session-cinnamon"
+            ;;
+        flux*)
+            WM="/usr/bin/startfluxbox"
+            ;;
+        gnome)
+            WM="/usr/bin/metacity"
+            ;;
+        icewm)
+            WM="/usr/bin/icewm"
+            ;;
+        kde)
+            WM="/usr/bin/kwin"
+            ;;
+        lxde)
+            WM="/usr/bin/openbox"
+            ;;
+        xfce)
+            WM="/usr/bin/xfwm4"
+            ;;
+	razorqt)
+            WM="/usr/bin/razor-session"
+            ;;
+        lxdqt)
+            WM="/usr/bin/lxqt-session"
+            ;;
+        *)
+            log_action_msg " desktop '${DESKTOP}' is not available"
+            log_end_msg 0
+            return 1
+            ;;
+    esac
 
-	if [ -x "${WM}" ]; then
-		case "${WM}" in 
-			"/usr/bin/kwin")
-				if [   -r /usr/share/xsessions/kde.desktop ] && \
-				   [ ! -r /usr/share/xsessions/kde-plasma.desktop ]; then
-					XSESSION="kde"
-				else
-					XSESSION="kde-plasma"
-				fi
-				;;
-			"/usr/bin/metacity")
-				XSESSION="gnome"
-				;;
-			"/usr/bin/startfluxbox")
-				XSESSION="fluxbox"
-				;;
-			"/usr/bin/xfwm4")
-				XSESSION="xfce"
-				;;
-			"/usr/bin/icewm")
-				XSESSION="IceWM"
-				;;
-			"/usr/bin/openbox")
-				XSESSION="LXDE"
-				;;
-			"/usr/bin/razor-session")
-				XSESSION="razor"
-				;;
-                        "/usr/bin/lxqt-session")
-                                XSESSION="lxde-qt"
-                                ;;
-			"/usr/bin/gnome-session-cinnamon")
-				XSESSION="cinnamon"
-				;;
-		esac
+    if [ -x "${WM}" ]; then
+        case "${WM}" in
+            "/usr/bin/kwin")
+            if [   -r /usr/share/xsessions/kde.desktop ] && \
+                [ ! -r /usr/share/xsessions/kde-plasma.desktop ]; then
+                XSESSION="kde"
+            else
+                XSESSION="kde-plasma"
+            fi
+            ;;
+            "/usr/bin/metacity")
+                XSESSION="gnome"
+                ;;
+            "/usr/bin/startfluxbox")
+                XSESSION="fluxbox"
+                ;;
+            "/usr/bin/xfwm4")
+                XSESSION="xfce"
+                ;;
+            "/usr/bin/icewm")
+                XSESSION="IceWM"
+                ;;
+            "/usr/bin/openbox")
+                XSESSION="LXDE"
+                ;;
+            "/usr/bin/razor-session")
+                XSESSION="razor"
+                ;;
+            "/usr/bin/lxqt-session")
+                XSESSION="lxqt"
+                ;;
+            "/usr/bin/gnome-session-cinnamon")
+		XSESSION="cinnamon"
+	        ;;
+        esac
 
-		log_action_begin_msg " setting up window manager '${WM}'"
-		echo "[Desktop]"		>  ${FLL_LIVE_USER_HOME}/.dmrc
-		echo "Session=${XSESSION}"	>> ${FLL_LIVE_USER_HOME}/.dmrc
-		chown "${FLL_LIVE_USER}:${FLL_LIVE_USER_GROUP}" "${FLL_LIVE_USER_HOME}/.dmrc"
-                if [ $WM = "/usr/bin/razor-session" ]; then
-                    update-alternatives --set x-window-manager /usr/bin/openbox >/dev/null
-		    log_end_msg "${?}"
-		     return 0
-		fi
+        log_action_begin_msg " setting up window manager '${WM}'"
+        echo "[Desktop]"		>  ${FLL_LIVE_USER_HOME}/.dmrc
+        echo "Session=${XSESSION}"	>> ${FLL_LIVE_USER_HOME}/.dmrc
+        chown "${FLL_LIVE_USER}:${FLL_LIVE_USER_GROUP}" "${FLL_LIVE_USER_HOME}/.dmrc"
+        if [ $WM = "/usr/bin/razor-session" ]; then
+            update-alternatives --set x-window-manager /usr/bin/openbox >/dev/null
+            log_end_msg "${?}"
+             return 0
+        fi
 
-                if [ $WM != "/usr/bin/lxqt-session" ]; then
-                    update-alternatives --set x-window-manager /usr/bin/openbox >/dev/null
-                    log_end_msg "${?}"
-                    return 0
-                fi
+        if [ $WM != "/usr/bin/lxqt-session" ]; then
+            update-alternatives --set x-window-manager /usr/bin/openbox >/dev/null
+            log_end_msg "${?}"
+            return 0
+        fi
 
-                update-alternatives --set x-window-manager "${WM}" >/dev/null
-                log_end_msg "${?}"
-                return 0
-	else
-		log_action_msg " desktop '${DESKTOP}' is not available"
-		log_end_msg 0
-		return 1
-	fi
+        update-alternatives --set x-window-manager "${WM}" >/dev/null
+        log_end_msg "${?}"
+        return 0
+    else
+        log_action_msg " desktop '${DESKTOP}' is not available"
+        log_end_msg 0
+        return 1
+    fi
 }
 
 case "${1}" in
-	start)
-		do_start
-		;;
-	stop)
-		;;
-	restart|force-reload)
-		echo "Error: argument '${1}' not supported" >&2
-		exit 3
-		;;
-	cinnamon|kde|gnome|flux*|xfce*|icewm|lxde |razorqt|lxde-qt)
-		DESKTOP="${1}"
-		do_start
-		;;
-	*)
-		echo "Usage: ${NAME} {start|stop}" >&2
-		exit 3
-		;;
+    start)
+        do_start
+        ;;
+    stop)
+        ;;
+    restart|force-reload)
+        echo "Error: argument '${1}' not supported" >&2
+        exit 3
+        ;;
+    cinnamon|kde|gnome|flux*|xfce*|icewm|lxde |razorqt|lxde-qt)
+        DESKTOP="${1}"
+        do_start
+        ;;
+    *)
+        echo "Usage: ${NAME} {start|stop}" >&2
+        exit 3
+        ;;
 esac
 
 :
